### ISSUE TITLE
not work with apache kafka 2.1.1 version and kafka-ui 0.5.0

### ISSUE THREAD

**Issue by EverCurse** [provectus/kafka-ui-charts#15]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/provectus/kafka-ui/issues) and [here](https://github.com/provectus/kafka-ui-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

2023-08-18 07:31:52,921 INFO  [parallel-4] o.a.k.c.u.AppInfoParser: Kafka version: 3.3.1
2023-08-18 07:31:52,921 INFO  [parallel-4] o.a.k.c.u.AppInfoParser: Kafka commitId: e23c59d00e687ff5
2023-08-18 07:31:52,921 INFO  [parallel-4] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1692343912921
2023-08-18 07:31:52,927 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: beta-bigdata-influence-kafka
2023-08-18 07:31:52,928 ERROR [parallel-2] c.p.k.u.s.StatisticsService: Failed to collect cluster sh-beta-infra-business-kafka info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster sh-beta-infra-business-kafka
	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Your installation details

install by helm chart 

kafka:
        clusters:
          - name: beta-infra-business-kafka
            bootstrapServers: *****.kafka.us-east-1.amazonaws.com:9092
          **- name: sh-beta-infra-business-kafka
            bootstrapServers: 10.83.43.46:9092,10.83.42.41:9092,10.83.41.194:9092**

something wrong with sh-beta-infra-business-kafka (kafka version 2.1.1)
but kafka of aws msk is work ok(msk version : 2.5.1)

### Steps to reproduce

1.install kafka-ui by helm chat
2.config the kafka of version 2.1.1

**Comment by Haarolean** [comment]
Hi, this repo is for issues related to helm charts. For issues with the app please raise an issue in provectus/kafka-ui.
Also, 0.5.x is [not supported](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)
