### ISSUE TITLE
java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default

### ISSUE THREAD

**Issue by machuecos** [provectus/kafka-ui-charts#33]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/provectus/kafka-ui/issues) and [here](https://github.com/provectus/kafka-ui-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I have been following the documentation to provide the `truststore.jks` and `keystore.jks` to be able to connect to the Kaka cluster via SSL https://docs.kafka-ui.provectus.io/configuration/helm-charts/configuration/ssl-example#create-secret exactly the same steps but Kafka-UI is not able to up the application in the pod and I get an error in loop. 

### Your installation details

1. Not UI appearing - Exception error
2. Helm chart version 0.7.6 / AppVersion 0.7.2
3. Application config (Helm templates generated related SSL)
```
# Source: kafka-ui/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
 name: ssl-secret
 namespace: strimzi-ui
type: Opaque
data:
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: xxxxxxxx
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: xxxxxxxx
---
# Source: kafka-ui/templates/configmap_fromValues.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-kafka-ui-fromvalues
  namespace: strimzi-ui
  labels:
    helm.sh/chart: kafka-ui-0.7.6
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.7.2"
    app.kubernetes.io/managed-by: Helm
data:
  config.yml: |-
    auth:
      type: disabled
    kafka:
      clusters:
      - bootstrapServers: my-strimzi-kafka-bootstrap.strimzi.svc:9093
        name: strimzi
    management:
      health:
        ldap:
          enabled: false
---
# Source: kafka-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-kafka-ui
  namespace: strimzi-ui
  labels:
    helm.sh/chart: kafka-ui-0.7.6
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.7.2"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-ui
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        checksum/config: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        checksum/configFromValues: a38cb5f6be79022948da18404f8f9864ad709911bcdd09f63bd23d136bfa2e49
        checksum/secret: 039e6066e12df180e8d5d6f869dfbc264c32e6447ea385105e7f777252231cdf
      labels:
        app.kubernetes.io/name: kafka-ui
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-kafka-ui
      securityContext:
        {}
      containers:
        - name: kafka-ui
          securityContext:
            {}
          image: docker.io/provectuslabs/kafka-ui:v0.7.2
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION
              value: /ssl/kafka.truststore.jks
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION
              value: /ssl/kafka.keystore.jks
            - name: SPRING_CONFIG_ADDITIONAL-LOCATION
              value: /kafka-ui/config.yml
          envFrom:
            - secretRef:
                name: ssl-secret    
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            {}
          volumeMounts:
            - mountPath: /ssl
              name: config-volume
            - name: kafka-ui-yaml-conf
              mountPath: /kafka-ui/
      volumes:
        - configMap:
            name: ssl-files
          name: config-volume
        - name: kafka-ui-yaml-conf
          configMap: 
            name: release-name-kafka-ui-fromvalues
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/kind
                operator: In
                values:
                - cluster-operator
            topologyKey: topology.kubernetes.io/zone
```
4. No IAAC code

### Steps to reproduce

Follow the steps from the documentation (SSL Example section): https://docs.kafka-ui.provectus.io/configuration/helm-charts/configuration/ssl-example#create-secret

### Screenshots

![image](https://github.com/provectus/kafka-ui-charts/assets/157005895/ab7490fc-437b-4729-9199-155052fd9d35)

### Logs

```
2024-04-21 10:03:38,638 DEBUG [parallel-2] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: Default
2024-04-21 10:03:38,639 ERROR [parallel-2] c.p.k.u.s.StatisticsService: Failed to collect cluster Default info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default
        at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$5(AdminClientServiceImpl.java:56)
        at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.Operators.error(Operators.java:198)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:135)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4480)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
        at reactor.core.publisher.Operators.complete(Operators.java:137)
        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:427)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: null
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at java.base/java.util.Properties.put(Properties.java:1301)
        at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$2(AdminClientServiceImpl.java:47)
        at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:67)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
        ... 16 common frames omitted
```

**Comment by Haarolean** [comment]
Hi, this repo is not maintained (https://github.com/provectus/kafka-ui/discussions/4255). Will be happy to look into your issue here: https://github.com/kafbat/kafka-ui. Please attach your config.yml as well :)

**Comment by indrekj** [comment]
@machuecos did you figure this out? I have exactly the same error

EDIT: oh I see there's kafbat-ui now. I'll look into that.
EDIT2: still the same issue
EDIT3: figured it out, I was missing bootstrap servers (KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS) :man_facepalming:

**Comment by marteloudini** [comment]
Hey,
i have the same issue, but with not SSL needed.
    app.kubernetes.io/version: v1.4.2
    helm.sh/chart: kafka-ui-1.6.0
im on windows 11; Podman Desktop; Kind.
i forward port for see on browser : 

<img width="1914" height="488" alt="Image" src="https://github.com/user-attachments/assets/5a7fa154-6798-4833-ac5e-e821eed1ddf9" />


my configmap kafka-ui:
```
   kafka:
      clusters:
        - name: my-cluster
          bootstrapServers: my-cluster-kafka-bootstrap:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
```

I see the home page, but when i clic on Broker, Consumer, Topics i have white page ?? (cf logs error below)

i have one topic (my-topic)
i have one consumer terminal actif
i have one producer terminal actif
i have 2 messages test.

My Deployment yaml from helm : 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafbat-ui-kafka-ui
  namespace: kafbat-ui
  uid: de7adf11-a4e7-4248-9a6d-cb949d6191e4
  resourceVersion: '283328'
  generation: 1
  creationTimestamp: '2026-02-17T14:30:24Z'
  labels:
    app.kubernetes.io/instance: kafbat-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/version: v1.4.2
    helm.sh/chart: kafka-ui-1.6.0
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: kafbat-ui
    meta.helm.sh/release-namespace: kafbat-ui
  selfLink: /apis/apps/v1/namespaces/kafbat-ui/deployments/kafbat-ui-kafka-ui
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  terminatingReplicas: 0
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2026-02-17T14:30:56Z'
      lastTransitionTime: '2026-02-17T14:30:24Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "kafbat-ui-kafka-ui-7955757f8d" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2026-02-19T07:24:03Z'
      lastTransitionTime: '2026-02-19T07:24:03Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafbat-ui
      app.kubernetes.io/name: kafka-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kafbat-ui
        app.kubernetes.io/name: kafka-ui
      annotations:
        checksum/config: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        checksum/configFromValues: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/secret: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      volumes:
        - name: kafka-ui-yaml-conf-configmap
          configMap:
            name: kafbat-ui-configmap
            defaultMode: 420
      containers:
        - name: kafka-ui
          image: ghcr.io/kafbat/kafka-ui:v1.4.2
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_CONFIG_ADDITIONAL-LOCATION
              value: /kafka-ui/config.yml
          resources: {}
          volumeMounts:
            - name: kafka-ui-yaml-conf-configmap
              mountPath: /kafka-ui/
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: kafbat-ui-kafka-ui
      serviceAccount: kafbat-ui-kafka-ui
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

**### my logs ERROR :** 

```
2026-02-19T08:07:30.278Z  WARN 1 --- [undedElastic-14] org.apache.kafka.clients.ClientUtils     : Couldn't resolve server my-cluster-kafka-bootstrap:9092 from bootstrap.servers as DNS resolution failed for my-cluster-kafka-bootstrap
2026-02-19T08:07:30.278Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.IllegalStateException: Error while creating AdminClient for the cluster my-cluster
	at io.kafbat.ui.service.AdminClientServiceImpl.lambda$createAdminClient$5(AdminClientServiceImpl.java:62) ~[!/:v1.4.2]
	at reactor.core.publisher.Mono.lambda$onErrorMap$29(Mono.java:3862) ~[reactor-core-3.7.12.jar!/:3.7.12]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.7.12.jar!/:3.7.12]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.7.12.jar!/:3.7.12]
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:231) ~[reactor-core-3.7.12.jar!/:3.7.12]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.7.12.jar!/:3.7.12]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.7.12.jar!/:3.7.12]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104) ~[reactor-core-3.7.12.jar!/:3.7.12]
		at reactor.core.publisher.Mono.block(Mono.java:1779) ~[reactor-core-3.7.12.jar!/:3.7.12]
		at io.kafbat.ui.service.ClustersStatisticsScheduler.updateStatistics(ClustersStatisticsScheduler.java:30) ~[!/:v1.4.2]
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
		at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
		at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.2.12.jar!/:6.2.12]
		at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.12.jar!/:6.2.12]
		at io.micrometer.observation.Observation.observe(Observation.java:498) ~[micrometer-observation-1.15.5.jar!/:1.15.5]
		at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.12.jar!/:6.2.12]
		at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:87) ~[spring-context-6.2.12.jar!/:6.2.12]
		at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.2.12.jar!/:6.2.12]
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
		... 3 common frames omitted
Caused by: org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:561) ~[kafka-clients-7.9.0-ccs.jar!/:na]
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:512) ~[kafka-clients-7.9.0-ccs.jar!/:na]
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:137) ~[kafka-clients-7.9.0-ccs.jar!/:na]
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39) ~[kafka-clients-7.9.0-ccs.jar!/:na]
	at io.kafbat.ui.service.AdminClientServiceImpl.lambda$createAdminClient$2(AdminClientServiceImpl.java:56) ~[!/:v1.4.2]
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:67) ~[reactor-core-3.7.12.jar!/:3.7.12]
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228) ~[reactor-core-3.7.12.jar!/:3.7.12]
	... 7 common frames omitted
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:104) ~[kafka-clients-7.9.0-ccs.jar!/:na]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:63) ~[kafka-clients-7.9.0-ccs.jar!/:na]
	at org.apache.kafka.clients.admin.internals.AdminBootstrapAddresses.fromConfig(AdminBootstrapAddresses.java:72) ~[kafka-clients-7.9.0-ccs.jar!/:na]
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:530) ~[kafka-clients-7.9.0-ccs.jar!/:na]
	... 13 common frames omitted

2026-02-19T08:07:55.273Z DEBUG 1 --- [    parallel-16] i.k.u.s.ClustersStatisticsScheduler      : Start getting metrics for kafkaCluster: my-cluster
2026-02-19T08:07:55.274Z  INFO 1 --- [undedElastic-15] o.a.k.clients.admin.AdminClientConfig    : AdminClientConfig values:
	auto.include.jmx.reporter = true
	bootstrap.controllers = []
	bootstrap.servers = [my-cluster-kafka-bootstrap:9092]
	client.dns.lookup = use_all_dns_ips
	client.id = kafbat-ui-admin-1771488475-104
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	enable.metrics.push = true
	metadata.max.age.ms = 300000
	metadata.recovery.strategy = none
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.max.ms = 1000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = GSSAPI
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.header.urlencode = false
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
```
